# Generated by Django 5.1.7 on 2025-05-02 13:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_options_alter_profile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email Doğrulandı'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Öğrenci'), ('community', 'Topluluk')], default='student', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='temporary_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Geçici Email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Doğrulama Kodu'),
        ),
    ]
