# Generated by Django 5.2 on 2025-05-26 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topluluklar', '0008_alter_post_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToplulukDegerlendirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etkinlik_puani', models.IntegerField(default=0)),
                ('aktiflik_puani', models.IntegerField(default=0)),
                ('yonetim_puani', models.IntegerField(default=0)),
                ('vaat_puani', models.IntegerField(default=0)),
                ('hakkaniyet_puani', models.IntegerField(default=0)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('degerlendiren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topluluk_degerlendirmeleri', to=settings.AUTH_USER_MODEL)),
                ('topluluk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degerlendirmeler', to='topluluklar.topluluklar')),
            ],
            options={
                'verbose_name': 'Topluluk Değerlendirmesi',
                'verbose_name_plural': 'Topluluk Değerlendirmeleri',
                'unique_together': {('topluluk', 'degerlendiren')},
            },
        ),
    ]
