# Generated by Django 5.1.7 on 2025-05-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_email_verified_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='profile',
            name='founded_date',
            field=models.DateField(blank=True, null=True, verbose_name='Kuruluş Tarihi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Profil Resmi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='members_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Üye Sayısı'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_media',
            field=models.JSONField(blank=True, null=True, verbose_name='Sosyal Medya Hesapları'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Web Sitesi'),
        ),
    ]
