# Generated by Django 5.1.7 on 2025-04-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topluluklar', '0002_rename_img_topluluklar_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topluluklar',
            old_name='image',
            new_name='img',
        ),
    ]
