# Generated by Django 5.1.7 on 2025-05-01 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_email_verified_profile_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_code',
            field=models.UUIDField(default=uuid.UUID('81638783-a576-4885-a9f3-04b4aa727e17')),
        ),
    ]
